import { AgentStage } from "@/types/agents";
import { McpServerDescriptor } from "@/types/mcp";

export const TRUEFORGE_STAGES: AgentStage[] = [
  {
    id: "web_search_mcp",
    stageNumber: 1,
    name: "Web Search MCP",
    shortName: "Search",
    agentRole: "Scholarly & Web Corpus Ingestion",
    description: "Model Context Protocol crawler querying academic preprints, SEC filings, and technical repositories.",
    status: "pending",
    progress: 0,
    logs: [],
  },
  {
    id: "company_agent",
    stageNumber: 2,
    name: "Company Agent",
    shortName: "Company",
    agentRole: "Primary IP & Tech Architecture",
    description: "Extracts technical architectures, patent disclosures, pilot yield metrics, and roadmaps.",
    status: "pending",
    progress: 0,
    logs: [],
  },
  {
    id: "competitor_agent",
    stageNumber: 3,
    name: "Competitor Agent",
    shortName: "Competitor",
    agentRole: "Adversarial Triangulation",
    description: "Cross-checks competing chemical/software architectures and benchmarks across independent labs.",
    status: "pending",
    progress: 0,
    logs: [],
  },
  {
    id: "market_agent",
    stageNumber: 4,
    name: "Market Agent",
    shortName: "Market",
    agentRole: "TAM & Unit Economics",
    description: "Models cost per unit trajectories, capex reduction curves, and commercial adoption timelines.",
    status: "pending",
    progress: 0,
    logs: [],
  },
  {
    id: "sandbox_analysis",
    stageNumber: 5,
    name: "Sandbox Analysis",
    shortName: "Sandbox",
    agentRole: "Numerical Code Execution",
    description: "Executes Monte Carlo regressions and AST linters in an isolated execution sandbox.",
    status: "pending",
    progress: 0,
    logs: [],
  },
  {
    id: "approval_required",
    stageNumber: 6,
    name: "Approval Required",
    shortName: "Approval",
    agentRole: "Human-in-the-Loop Signoff",
    description: "Researcher reviews synthesized facts, grounded DOIs, and signs off before report generation.",
    status: "pending",
    progress: 0,
    logs: [],
  },
  {
    id: "generate_report",
    stageNumber: 7,
    name: "Generate Report",
    shortName: "Report",
    agentRole: "Dossier Synthesis & Export",
    description: "Compiles verified executive summary, market analysis, competitor breakdown, and recommendations.",
    status: "pending",
    progress: 0,
    logs: [],
  },
];

export const CONNECTED_MCP_SERVERS: McpServerDescriptor[] = [
  {
    name: "arxiv-academic-mcp",
    uri: "mcp://arxiv.internal.trueforge/v1",
    status: "connected",
    description: "Live connection to 2.4M arXiv preprints with semantic vector filtering.",
    toolsExposed: ["search_papers", "fetch_abstract", "extract_latex_equations"],
  },
  {
    name: "uspto-patents-mcp",
    uri: "mcp://uspto.internal.trueforge/v1",
    status: "connected",
    description: "Direct claim parsing across US and WIPO patent registries.",
    toolsExposed: ["query_claims", "check_assignee_portfolio", "verify_patent_status"],
  },
  {
    name: "sec-edgar-mcp",
    uri: "mcp://edgar.internal.trueforge/v1",
    status: "connected",
    description: "Automated SEC 10-K, 10-Q, and 8-K financial disclosure ingestion.",
    toolsExposed: ["parse_10k_risk_factors", "extract_capex_tables", "get_earnings_transcript"],
  },
  {
    name: "sandbox-python-mcp",
    uri: "mcp://sandbox.internal.trueforge/v1",
    status: "connected",
    description: "Secure, isolated WASM Python 3.12 numerical execution environment.",
    toolsExposed: ["exec_python_script", "run_monte_carlo", "check_math_consistency"],
  },
];
