"use client";

import React, { useState } from "react";
import Link from "next/link";
import { FileText, PlusCircle, Search, ShieldCheck, ArrowRight, Clock } from "lucide-react";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { ReportEmptyState } from "@/features/reports/ReportEmptyState";
import { useResearch } from "@/lib/store";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { formatDate } from "@/lib/utils";

export default function ReportsPage() {
  const { reports } = useResearch();
  const [search, setSearch] = useState("");

  const filteredReports = reports.filter(
    (r) =>
      r.title.toLowerCase().includes(search.toLowerCase()) ||
      r.query.toLowerCase().includes(search.toLowerCase()) ||
      r.executiveSummary.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <DashboardLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-border/80">
          <div>
            <div className="flex items-center gap-2 text-xs font-mono text-purple-400 font-bold uppercase tracking-wider mb-1">
              <FileText className="h-3.5 w-3.5" />
              <span>Synthesized Intelligence</span>
            </div>
            <h1 className="text-2xl font-bold tracking-tight text-foreground font-sans">
              Compiled Reports ({reports.length})
            </h1>
            <p className="text-xs text-muted-foreground font-sans mt-0.5">
              Verified deep research dossiers generated by TrueForge multi-agent swarms.
            </p>
          </div>

          <Link href="/research">
            <Button variant="glow" size="sm" className="h-9 px-4 rounded-xl text-xs font-mono font-bold flex items-center gap-2">
              <PlusCircle className="h-4 w-4" />
              <span>New Investigation</span>
            </Button>
          </Link>
        </div>

        {/* Search Bar if reports exist */}
        {reports.length > 0 && (
          <div className="relative max-w-md">
            <input
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search reports by title, query, or findings..."
              className="w-full h-10 rounded-xl border border-border/80 bg-card/60 px-3.5 pl-9 text-xs text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-purple-500 font-sans"
            />
            <Search className="h-4 w-4 text-muted-foreground absolute left-3 top-3" />
          </div>
        )}

        {/* Reports Catalog or Empty State */}
        {reports.length === 0 ? (
          <ReportEmptyState />
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredReports.map((report) => (
              <div
                key={report.id}
                className="p-6 rounded-3xl border border-border/80 bg-card/60 hover:border-purple-500/40 hover:bg-card/90 transition-all flex flex-col justify-between space-y-4 group shadow-xl"
              >
                <div className="space-y-2.5">
                  <div className="flex items-center justify-between">
                    <Badge variant="purple" className="text-[10px] font-mono capitalize">
                      {report.depth}
                    </Badge>
                    <div className="flex items-center gap-1 text-[11px] font-mono text-emerald-400">
                      <ShieldCheck className="h-3.5 w-3.5" />
                      <span>{report.confidenceScore}%</span>
                    </div>
                  </div>

                  <h3 className="text-base font-bold text-foreground group-hover:text-purple-300 transition-colors line-clamp-2">
                    {report.title}
                  </h3>

                  <p className="text-xs text-muted-foreground line-clamp-3 leading-relaxed font-sans">
                    {report.executiveSummary}
                  </p>
                </div>

                <div className="pt-3 border-t border-border/50 flex items-center justify-between text-xs font-mono">
                  <span className="text-muted-foreground flex items-center gap-1">
                    <Clock className="h-3 w-3" />
                    <span>{formatDate(report.createdAt)}</span>
                  </span>

                  <Link
                    href={`/report/${report.id}`}
                    className="text-purple-400 font-semibold group-hover:translate-x-0.5 transition-transform flex items-center gap-1"
                  >
                    <span>Read Dossier</span>
                    <ArrowRight className="h-3 w-3" />
                  </Link>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
